import type { Metadata } from "next";
import { Fira_Code, Merriweather, Oxanium } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";

// Load the fonts with proper variable names
const sans = Oxanium({
  variable: "--font-sans",
  subsets: ["latin"],
});
const serif = Merriweather({
  variable: "--font-serif",
  subsets: ["latin"],
  weight: ["400", "700"], // Add appropriate weights as needed
});
const mono = Fira_Code({
  variable: "--font-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${sans.variable} ${serif.variable} ${mono.variable} antialiased`}
      >
        <Toaster />
        {children}
      </body>
    </html>
  );
}
